import fs from 'node:fs/promises';
import path from 'node:path';

/*
 * ================================================================
 * SEMS+ Offline Replay Builder
 *
 * Reads:
 *
 *   C:\agent-web-cache\semsplus\latest.json
 *   C:\agent-web-cache\semsplus\collections\<collection>\
 *
 * Generates:
 *
 *   C:\agent-web-cache\semsplus\replay\latest\
 *
 * The replay site:
 *
 * - contains no live SEMS+ URLs
 * - contains no external resources
 * - contains no credentials/cookies
 * - makes no network requests
 * - provides local clickable navigation
 * - provides local text search/filtering
 *
 * ================================================================
 */

const CACHE_DIR =
  process.env.CACHE_DIR ??
  'C:\\agent-web-cache\\semsplus';

const COLLECTIONS_DIR =
  path.join(
    CACHE_DIR,
    'collections'
  );

const REPLAY_ROOT =
  path.join(
    CACHE_DIR,
    'replay'
  );

const REPLAY_DIR =
  path.join(
    REPLAY_ROOT,
    'latest'
  );

/*
 * ---------------------------------------------------------------
 * Fixed allowlist of views.
 *
 * The replay builder does NOT discover arbitrary files.
 * ---------------------------------------------------------------
 */

const VIEWS = Object.freeze([
  {
    control: 'dashboard',
    slug: 'dashboard',
    label: 'Dashboard'
  },
  {
    control: 'devices',
    slug: 'devices',
    label: 'Devices'
  },
  {
    control: 'alarms',
    slug: 'alarms',
    label: 'Alarms'
  },
  {
    control: 'powerCurve',
    slug: 'power-curve',
    label: 'Power Curve'
  },
  {
    control: 'energyMonitoring',
    slug: 'energy-monitoring',
    label: 'Energy Monitoring'
  },
  {
    control: 'generationComparison',
    slug: 'generation-comparison',
    label: 'Generation Comparison'
  },
  {
    control: 'heatmap',
    slug: 'heatmap',
    label: 'Heatmap'
  }
]);

/*
 * ---------------------------------------------------------------
 * HTML escaping.
 *
 * Snapshot text is DATA, not trusted HTML.
 * ---------------------------------------------------------------
 */

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

/*
 * ---------------------------------------------------------------
 * Common CSP.
 *
 * There are deliberately:
 *
 * - no external scripts
 * - no images
 * - no network connections
 * - no forms
 * - no frames
 *
 * JavaScript is inline and generated by us solely for local search.
 * ---------------------------------------------------------------
 */

const CSP = [
  "default-src 'none'",
  "style-src 'unsafe-inline'",
  "script-src 'unsafe-inline'",
  "img-src 'none'",
  "connect-src 'none'",
  "font-src 'none'",
  "media-src 'none'",
  "object-src 'none'",
  "frame-src 'none'",
  "form-action 'none'",
  "base-uri 'none'"
].join('; ');

/*
 * ---------------------------------------------------------------
 * Navigation bar.
 * ---------------------------------------------------------------
 */

function renderNavigation(
  currentSlug
) {
  return VIEWS
    .map((view) => {
      const current =
        view.slug === currentSlug;

      const className =
        current
          ? 'nav-link active'
          : 'nav-link';

      return `
        <a
          class="${className}"
          href="./${view.slug}.html"
        >${escapeHtml(view.label)}</a>
      `;
    })
    .join('\n');
}

/*
 * ---------------------------------------------------------------
 * CSS.
 *
 * No external stylesheet is used.
 * ---------------------------------------------------------------
 */

function renderCss() {
  return `
    :root {
      font-family:
        system-ui,
        -apple-system,
        BlinkMacSystemFont,
        "Segoe UI",
        sans-serif;

      color-scheme: light dark;
    }

    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      padding: 0;
      line-height: 1.5;
    }

    header {
      padding: 18px 24px;
      border-bottom:
        1px solid
        color-mix(
          in srgb,
          currentColor 20%,
          transparent
        );
    }

    .header-row {
      display: flex;
      gap: 16px;
      align-items: center;
      flex-wrap: wrap;
    }

    h1 {
      margin: 0;
      font-size: 22px;
    }

    .offline-badge {
      display: inline-block;
      border: 1px solid currentColor;
      border-radius: 999px;
      padding: 3px 9px;
      font-size: 12px;
      font-weight: 700;
    }

    .collection {
      margin-top: 6px;
      opacity: 0.75;
      font-size: 13px;
    }

    nav {
      display: flex;
      gap: 7px;
      flex-wrap: wrap;
      padding: 14px 24px;
      border-bottom:
        1px solid
        color-mix(
          in srgb,
          currentColor 20%,
          transparent
        );
    }

    .nav-link {
      color: inherit;
      text-decoration: none;
      border: 1px solid currentColor;
      border-radius: 6px;
      padding: 6px 10px;
    }

    .nav-link:hover {
      text-decoration: underline;
    }

    .nav-link.active {
      font-weight: 700;
      outline: 2px solid currentColor;
    }

    main {
      max-width: 1100px;
      margin: 0 auto;
      padding: 24px;
    }

    .search-box {
      margin-bottom: 20px;
    }

    .search-box label {
      display: block;
      font-weight: 700;
      margin-bottom: 6px;
    }

    .search-box input {
      width: 100%;
      max-width: 600px;
      padding: 10px 12px;
      font: inherit;
      border:
        1px solid
        color-mix(
          in srgb,
          currentColor 35%,
          transparent
        );
      border-radius: 6px;
    }

    .status {
      margin-top: 7px;
      font-size: 13px;
      opacity: 0.75;
    }

    .snapshot {
      border:
        1px solid
        color-mix(
          in srgb,
          currentColor 20%,
          transparent
        );

      border-radius: 8px;
      overflow: hidden;
    }

    .line {
      padding: 5px 12px;
      border-bottom:
        1px solid
        color-mix(
          in srgb,
          currentColor 10%,
          transparent
        );

      white-space: pre-wrap;
      overflow-wrap: anywhere;
    }

    .line:last-child {
      border-bottom: 0;
    }

    .line:hover {
      background:
        color-mix(
          in srgb,
          currentColor 7%,
          transparent
        );
    }

    .metadata {
      margin-bottom: 18px;
      padding: 12px;
      border:
        1px solid
        color-mix(
          in srgb,
          currentColor 15%,
          transparent
        );

      border-radius: 8px;
    }

    .metadata strong {
      display: inline-block;
      min-width: 110px;
    }

    .home-grid {
      display: grid;
      grid-template-columns:
        repeat(
          auto-fit,
          minmax(220px, 1fr)
        );

      gap: 14px;
    }

    .home-card {
      display: block;
      color: inherit;
      text-decoration: none;
      border: 1px solid currentColor;
      border-radius: 8px;
      padding: 18px;
    }

    .home-card:hover {
      text-decoration: underline;
    }

    .home-card h2 {
      margin-top: 0;
    }

    [hidden] {
      display: none !important;
    }
  `;
}

/*
 * ---------------------------------------------------------------
 * Local-only search JavaScript.
 *
 * This code:
 *
 * - does not fetch()
 * - does not use XMLHttpRequest
 * - does not connect anywhere
 * - only hides/shows cached text lines
 * ---------------------------------------------------------------
 */

function renderSearchScript() {
  return `
    (() => {
      'use strict';

      const input =
        document.getElementById(
          'replay-search'
        );

      const status =
        document.getElementById(
          'search-status'
        );

      const lines =
        Array.from(
          document.querySelectorAll(
            '[data-replay-line]'
          )
        );

      function update() {
        const query =
          input.value
            .trim()
            .toLowerCase();

        let visible = 0;

        for (const line of lines) {
          const text =
            line.textContent
              .toLowerCase();

          const match =
            !query ||
            text.includes(query);

          line.hidden =
            !match;

          if (match) {
            visible += 1;
          }
        }

        if (!query) {
          status.textContent =
            lines.length +
            ' cached lines';
        } else {
          status.textContent =
            visible +
            ' matching lines';
        }
      }

      input.addEventListener(
        'input',
        update
      );

      update();
    })();
  `;
}

/*
 * ---------------------------------------------------------------
 * Render one replay page.
 * ---------------------------------------------------------------
 */

function renderViewPage({
  collection,
  view,
  text,
  metadata
}) {
  const lines =
    text
      .split(/\r?\n/)
      .filter(
        line =>
          line.trim().length > 0
      );

  const renderedLines =
    lines
      .map(
        (line, index) => `
          <div
            class="line"
            data-replay-line
            data-line-number="${index + 1}"
          >${escapeHtml(line)}</div>
        `
      )
      .join('\n');

  const capturedAt =
    metadata?.capturedAt ??
    'unknown';

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <meta
    http-equiv="Content-Security-Policy"
    content="${escapeHtml(CSP)}"
  >

  <meta
    name="referrer"
    content="no-referrer"
  >

  <meta
    name="viewport"
    content="width=device-width, initial-scale=1"
  >

  <title>
    ${escapeHtml(view.label)} - Offline SEMS+ Replay
  </title>

  <style>
${renderCss()}
  </style>
</head>

<body>

<header>
  <div class="header-row">

    <h1>
      Offline SEMS+ Replay
    </h1>

    <span class="offline-badge">
      OFFLINE CACHE
    </span>

  </div>

  <div class="collection">
    Collection:
    ${escapeHtml(collection)}
  </div>
</header>

<nav aria-label="Cached SEMS+ views">
${renderNavigation(view.slug)}
</nav>

<main>

  <h2>
    ${escapeHtml(view.label)}
  </h2>

  <div class="metadata">
    <div>
      <strong>Source:</strong>
      sanitized cache
    </div>

    <div>
      <strong>Captured:</strong>
      ${escapeHtml(capturedAt)}
    </div>

    <div>
      <strong>Network:</strong>
      not required
    </div>
  </div>

  <div class="search-box">

    <label for="replay-search">
      Search this cached view
    </label>

    <input
      id="replay-search"
      type="search"
      autocomplete="off"
      placeholder="e.g. Offline, inverter, alarm..."
    >

    <div
      id="search-status"
      class="status"
      aria-live="polite"
    ></div>

  </div>

  <section
    class="snapshot"
    aria-label="${escapeHtml(view.label)} cached data"
  >
${renderedLines}
  </section>

</main>

<script>
${renderSearchScript()}
</script>

</body>
</html>`;
}

/*
 * ---------------------------------------------------------------
 * Render replay home page.
 * ---------------------------------------------------------------
 */

function renderIndexPage(
  collection,
  viewMetadata
) {
  const cards =
    VIEWS
      .map((view) => {

        const metadata =
          viewMetadata.get(
            view.control
          );

        const capturedAt =
          metadata?.capturedAt ??
          'unknown';

        return `
          <a
            class="home-card"
            href="./${view.slug}.html"
          >

            <h2>
              ${escapeHtml(view.label)}
            </h2>

            <div>
              Open cached view
            </div>

            <div class="collection">
              Captured:
              ${escapeHtml(capturedAt)}
            </div>

          </a>
        `;
      })
      .join('\n');

  return `<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">

  <meta
    http-equiv="Content-Security-Policy"
    content="${escapeHtml(CSP)}"
  >

  <meta
    name="referrer"
    content="no-referrer"
  >

  <meta
    name="viewport"
    content="width=device-width, initial-scale=1"
  >

  <title>
    Offline SEMS+ Replay
  </title>

  <style>
${renderCss()}
  </style>

</head>

<body>

<header>

  <div class="header-row">

    <h1>
      Offline SEMS+ Replay
    </h1>

    <span class="offline-badge">
      OFFLINE CACHE
    </span>

  </div>

  <div class="collection">
    Collection:
    ${escapeHtml(collection)}
  </div>

</header>

<main>

  <p>
    This interface contains only data copied from
    the sanitized SEMS+ cache.
  </p>

  <p>
    Choose a cached view:
  </p>

  <div class="home-grid">
${cards}
  </div>

</main>

</body>
</html>`;
}

/*
 * ================================================================
 * Main
 * ================================================================
 */

const latestPath =
  path.join(
    CACHE_DIR,
    'latest.json'
  );

const latest =
  JSON.parse(
    await fs.readFile(
      latestPath,
      'utf8'
    )
  );

const collection =
  latest.collection;

/*
 * Collection names must be a simple directory name.
 *
 * Prevent path traversal such as ../../something.
 */

if (
  typeof collection !== 'string' ||
  !/^[A-Za-z0-9._-]+$/.test(
    collection
  )
) {
  throw new Error(
    'Invalid collection name in latest.json'
  );
}

const collectionDir =
  path.resolve(
    COLLECTIONS_DIR,
    collection
  );

const collectionsRoot =
  path.resolve(
    COLLECTIONS_DIR
  ) + path.sep;

if (
  !collectionDir.startsWith(
    collectionsRoot
  )
) {
  throw new Error(
    'Collection path escaped collections directory'
  );
}

console.log(
  `Source collection: ${collection}`
);

console.log(
  `Source directory:  ${collectionDir}`
);

console.log('');

/*
 * ---------------------------------------------------------------
 * Load only the fixed allowlisted files.
 * ---------------------------------------------------------------
 */

const loadedViews =
  [];

const viewMetadata =
  new Map();

for (const view of VIEWS) {

  const textPath =
    path.join(
      collectionDir,
      `${view.slug}.txt`
    );

  const metadataPath =
    path.join(
      collectionDir,
      `${view.slug}.json`
    );

  const text =
    await fs.readFile(
      textPath,
      'utf8'
    );

  const metadata =
    JSON.parse(
      await fs.readFile(
        metadataPath,
        'utf8'
      )
    );

  /*
   * Make sure the metadata corresponds to
   * the expected hard-coded control.
   */

  if (
    metadata.control !==
    view.control
  ) {
    throw new Error(
      `${view.slug}: metadata control mismatch`
    );
  }

  /*
   * Important:
   *
   * We deliberately do NOT copy metadata.url
   * into the replay site.
   */

  loadedViews.push({
    view,
    text,
    metadata
  });

  viewMetadata.set(
    view.control,
    metadata
  );
}

/*
 * ---------------------------------------------------------------
 * Build into a temporary directory first.
 * ---------------------------------------------------------------
 */

await fs.mkdir(
  REPLAY_ROOT,
  {
    recursive: true
  }
);

const tempDir =
  path.join(
    REPLAY_ROOT,
    `.latest-tmp-${process.pid}`
  );

await fs.rm(
  tempDir,
  {
    recursive: true,
    force: true
  }
);

await fs.mkdir(
  tempDir,
  {
    recursive: true
  }
);

/*
 * Home page.
 */

await fs.writeFile(
  path.join(
    tempDir,
    'index.html'
  ),

  renderIndexPage(
    collection,
    viewMetadata
  ),

  'utf8'
);

/*
 * Seven replay pages.
 */

for (
  const item of loadedViews
) {

  const html =
    renderViewPage({
      collection,
      view:
        item.view,
      text:
        item.text,
      metadata:
        item.metadata
    });

  const outputPath =
    path.join(
      tempDir,
      `${item.view.slug}.html`
    );

  await fs.writeFile(
    outputPath,
    html,
    'utf8'
  );

  console.log(
    `Generated: ${item.view.slug}.html`
  );
}

/*
 * ---------------------------------------------------------------
 * Safe replay manifest.
 *
 * Notice that no SEMS+ URL is copied here.
 * ---------------------------------------------------------------
 */

const replayManifest = {
  generatedAt:
    new Date().toISOString(),

  collection,

  source:
    'sanitized-cache',

  networkRequired:
    false,

  views:
    VIEWS.map(
      view => ({
        control:
          view.control,

        label:
          view.label,

        file:
          `${view.slug}.html`
      })
    )
};

await fs.writeFile(
  path.join(
    tempDir,
    'replay-manifest.json'
  ),

  JSON.stringify(
    replayManifest,
    null,
    2
  ),

  'utf8'
);

/*
 * ---------------------------------------------------------------
 * Replace replay/latest only after the new replay has been built.
 * ---------------------------------------------------------------
 */

await fs.rm(
  REPLAY_DIR,
  {
    recursive: true,
    force: true
  }
);

await fs.rename(
  tempDir,
  REPLAY_DIR
);

console.log('');
console.log(
  'REPLAY BUILD SUCCESS'
);

console.log(
  `Directory: ${REPLAY_DIR}`
);

console.log(
  `Views: ${VIEWS.length}`
);